import { ProductsI } from "../interfaces/products.interface";

export const state: ProductsI = {
  promotions: [
    {
      id: 1,
      name: "Promotion 1",
      description: "Promotion 1 description",
      image_url: "https://via.placeholder.com/150",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 2,
      name: "grand slam indoor.",
      description: "",
      image_url: "https://via.placeholder.com/150",
      price: 41.99,
      discount_price: 32.99,
      discount_percentage: 18,
      store_name: "Robert's store",
    },
    {
      id: 3,
      name: "grand slam indoor.",
      description: "",
      image_url: "https://via.placeholder.com/150",
      price: 41.99,
      discount_price: 32.99,
      discount_percentage: 18,
      store_name: "Robert's store",
    },
    {
      id: 4,
      image_url: "img/products/home/1.jpg",
      price : 670.00,
      discount_percentage: 18,
      discount_price: 567.99,
      name: "Korea Long Sofa Fabric In Blue Navy Color",
      store_name: '',
      description : '',
    },
    {
      id: 5,
      image_url: "img/products/home/2.jpg",
      description: "Out Of Stock",
      discount_percentage: 18,
      name : 'Aroma rice cooker',
      price : 670.00,
      discount_price: 567.99,
      store_name: '',
    },
    {
      id: 6,
      image_url: "img/products/home/2.jpg",
      description: "Out Of Stock",
      discount_percentage: 20,
      name : 'Crema dental Colgate + cepillo dental',
      price : 11500,
      discount_price: 10200,
      store_name: 'Merkado',
    },
  ],
  products : [
    {
      id: 1,
      image_url: "https://via.placeholder.com/150",
      name: "Product 1",
      description: "Product 1 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 2,
      image_url: "https://via.placeholder.com/150",
      name: "Product 2",
      description: "Product 2 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 3,
      image_url: "https://via.placeholder.com/150",
      name: "Product 3",
      description: "Product 3 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 4,
      image_url: "https://via.placeholder.com/150",
      name: "Product 4",
      description: "Product 4 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 5,
      image_url: "https://via.placeholder.com/150",
      name: "Product 5",
      description: "Product 5 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 6,
      image_url: "https://via.placeholder.com/150",
      name: "Product 6",
      description: "Product 6 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 7,
      image_url: "https://via.placeholder.com/150",
      name: "Product 7",
      description: "Product 7 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
    {
      id: 8,
      image_url: "https://via.placeholder.com/150",
      name: "Product 8",
      description: "Product 8 description",
      price: 100,
      discount_price: 50,
      discount_percentage: 50,
      store_name: "Store 1",
    },
  ]
}
